.PHONY: clean All

All:
	@echo "----------Building project:[ chat_select - Debug ]----------"
	@cd "chat_select" && "$(MAKE)" -f  "chat_select.mk"
clean:
	@echo "----------Cleaning project:[ chat_select - Debug ]----------"
	@cd "chat_select" && "$(MAKE)" -f  "chat_select.mk" clean
